### ISSUE TITLE
Install FREME-NER from oficial mirror

### ISSUE THREAD

**Issue by sandroacoelho** [freme-project/freme-docker#1]
Install FREME-NER from oficial mirror
- https://github.com/freme-project/freme-docker/blob/master/freme-ner/Dockerfile#L3

**Comment by jnehring** [comment]
I dont understand. Can you please explain what this issue is about?

**Comment by sandroacoelho** [comment]
Hi @jnehring 

This issue was applicable to the first version (under freme-ner-old), because I used pre-compiled jars from Dropbox.

Best,
