### ISSUE TITLE
change passwords

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-docker#10]
Currently the system defines static default passwords. These should be configurable so every installation uses their own set of passwords.

Currently it is unclear how this will work.

**Comment by sandroacoelho** [comment]
Hi @jnehring,

As you have proposed, you will offer pre-built versioned images who contains software layers that FREME needs to run. 

Under this images, we can offer Dockerfiles just with variables (passwords, config files) etc

E.g:

```
FROM fremeproject/freme-ner-en
ADD config/*  /opt/freme-ner/config/
ADD bin/*  /opt/freme-ner/bin/
```

It would be reliable, will save a lot of time and is a breakthrough, if we compare with our [first version](https://github.com/freme-project/freme-docker/blob/master/freme-ner-old/freme-ner/Dockerfile) that build all from scratch.

A minimal configuration work is still needed to be performed and is acceptable.

If we would have a state-of-art in devops, we can be inspired in some cloud services (such heroku) who have a smart approach that defines automatically users, passwords, owners (for databases) etc., being agnostic with this metadata. I bet that we can do this with Docker, but first I need to check the documentation. Let's try

**Comment by jnehring** [comment]
We can set passwords for
- mysql through environment variables / docker-compose.yml (see [wiki](https://github.com/freme-project/freme-docker/wiki))
- virtuoso through environment variables / docker-compose.yml (see [wiki](https://github.com/freme-project/freme-docker/wiki))
- solr - i think solr does not use any passwords
- we can pass the passwords to FREME via environment variables (see [spring boot doc](docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html))
- FREME specifies an admin password in the configuration, which can be set via environment variable also (see [spring boot doc](docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html))

**Comment by jnehring** [comment]
This issue is solved.
