### ISSUE TITLE
Research combination of docker images

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-docker#12]
From [making FREME assets available](https://docs.google.com/document/d/1qlA2LyqKwGeO_ds9hFNDzKT_Wd_C7wv6z4CIK_PLiSo/edit#)

We need to find out how to add datasets to FREME NER and virtuoso. Check if we can combine Docker images. So we create a docker image for each dataset / language and then create combinations for each partner.

**Comment by jnehring** [comment]
Any news here? I still dont understand how this will work.

**Comment by sandroacoelho** [comment]
Hi @jnehring ,

Going deeper in Virtuoso/Docker documentation, I've found this [tutorial](http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtuosoDocker).  Talking with a friend about this problem, he advises me keep data out of the container to take some advantages,  like
- Backup / restore your data when you need/want;
- Our application needs Read/Write operations. When we use docker images without "volumes feature", we have just read operations for persistent data. You are able to modify, but when you power off the docker image, these data will be lost.

Maybe we can offer some combinations off datasets providing pre-built files, allowing users to integrate their own data using volumes.  What do you think?

**Comment by jnehring** [comment]
This will be handled by #16 and #17
