### ISSUE TITLE
FREME NER does not work in docker

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-docker#15]
When I call FREME NER in docker then I get [this exception](https://github.com/freme-project/freme-docker/files/474235/freme-ner-exception.txt). It causes the JVM to stop and therefore the whole broker shuts down.

@sandroacoelho can you please take a look at the error message and find out what is wrong?

**Comment by sandroacoelho** [comment]
Hi @jnehring ,

It seems that [solr-solrj-5.2.1.jar](http://central.maven.org/maven2/org/apache/solr/solr-solrj/5.2.1/) is not in classpath

**Comment by jnehring** [comment]
ok thank you. i remember this problem and will fix it.

**Comment by jnehring** [comment]
This cannot be the problem. I checked the configuration and solr 5.2.1 is on the classpath. You can see the freme-package that runs inside of the container here: https://github.com/freme-project/freme-docker/tree/master/freme-package

You can reproduce the problem without docker:

```
git clone https://github.com/freme-project/freme-docker
cd freme-docker/freme-package/
mvn package
cd target/freme-package
chmod +x bin/*
vim config/application.properties # change path to the models location
bin/start_server.sh
# wait until freme has started (tail -f logs/broker.log)
curl -X POST -H "Content-Type: text/plain" -H "Accept: text/turtle" -d 'The Eiffel Tower (/ˈaɪfəl ˈtaʊər/ EYE-fəl TOWR; French: tour Eiffel [tuʁ‿ɛfɛl] About this sound listen) is a wrought iron lattice tower on the Champ de Mars in Paris.' "http://localhost:8080/e-entity/freme-ner/documents?language=en&mode=spot"
```

**Comment by m1ci** [comment]
weird, the stack trace says:
`java.lang.NoClassDefFoundError: org/apache/solr/client/solrj/impl/HttpSolrClient`

**Comment by jnehring** [comment]
Ok I get a different error from when I run it inside of docker then when I run it from outside of docker (see [this commit](https://github.com/freme-project/freme-docker/issues/15#issuecomment-249820549).

**Comment by jnehring** [comment]
The maven configuration was wrong and the wrong artifact was pulled in. I could fix the issue.
