### ISSUE TITLE
Add large datasets to Virtuoso

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-docker#17]

**Comment by sandroacoelho** [comment]
Virtuoso is an RDBMS/Triple store, but checking the documentation it is possible to use copy and paste to distribute the datasets. Please check it out in this [technical tutorial](http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtuosoDocker).

I am now working on in a small example. When I have it done, I will send you.

**Comment by jnehring** [comment]
Next step: Add the remaining dbpedia datasets and Europeana

**Comment by jnehring** [comment]
The files you produced for Virtuoso are ~ 200 GB. This is so large, we should give it a second thought if we really need all the data. Currently the datasets on virtuoso are way smaller. Did you upload the whole datasets? I think we need the labels only, so all triples with rdfs:label property.

@m1ci  is this correct? Or do we need other data also?

**Comment by m1ci** [comment]
the types are also needed. Triple having `rdf:type` predicate should be added.

**Comment by jnehring** [comment]
@sandroacoelho sorry but please do this again. This time add to the virtuoso only triples with rdfs:label and rdf:type from all dbpedia datasets and europeana.

In above I wrote rdfs:type but I think this does not exist and it should be rdf:type

**Comment by sandroacoelho** [comment]
Hi @jnehring : not problem at all. I will reindex it today just with labels and types.

**Comment by jnehring** [comment]
Hi @sandroacoelho . In last developers call we noted several tasks:
- Upload the virtuoso data folder for all standard datasets (dbpedia in all FREME languages and europeana) to freme-dev
- Create the data folder for Virtuoso and Solr for all datasets and upload it.

What is the state of these tasks?

**Comment by sandroacoelho** [comment]
Hi @jnehring 

I did not tell you (sorry),  but all of them are available at rv1443.1blu.de

SOLR DBpedia: /home/u231015/dumps/solr_dbpedia

SOLR DBpedia Europeana: /home/u231015/dumps/solr_dbpedia_europeana

Virtuoso DBpedia 2016-04 (Just with labels and types for en, de, nl, fr, it, es and ru) : 

/home/u231015/dumps/2016-04/virtuoso-dbpedia/

Virtuoso DBpedia 2016-04 + Europeana: 

/home/u231015/dumps/2016-04/virtuoso-dbpedia-europeana/

Best,

**Comment by jnehring** [comment]
Great thanks! Will test it as soon as possible

**Comment by jnehring** [comment]
Hey @sandroacoelho I think this is a mis understanding. We need
1. Dumps of Solr and Virtuoso with DBPedia in en, de, nl, fr, it, es and ru and Europeana
2. Dumps of Solr and Virtuoso with all datasets ([complete list here](https://docs.google.com/document/d/1UNPkoCjScO5HPXYs4DxzfWjOe0kX0sSbj3h07surY5E/edit#heading=h.1vplesoqybpl))

I think that 1) is solved, but 2) is not solved.

**Comment by sandroacoelho** [comment]
Hi @jnehring,

I can add the missing datasets. No problem. I will tell you when it is ready.

Best,

**Comment by sandroacoelho** [comment]
TODOs:
- [x] Move all data to the Default Graph http://www.freme-project.eu/datasets/types
- [ ]  Install DBpedia Ontology

**Comment by m1ci** [comment]
> Move all data to the Default Graph http://www.freme-project.eu/datasets/types

There is no need.

> Install DBpedia Ontology

Yes, please @sandroacoelho (cc @jnehring) add the latest dbpedia ontology into the virtuoso in the docker image
http://downloads.dbpedia.org/2016-04/dbpedia_2016-04.owl

**Comment by sandroacoelho** [comment]
Hi @jnehring,

All dumps will be available under /home/u231015/dumps

├── agroknow
│   ├── mysql
│   ├── solr
│   ├── virtuoso
├── iminds
│   ├── mysql
│   ├── solr
│   └── virtuoso
├── vtec
│   ├── mysql
│   ├── solr
│   └── virtuoso
└── wripl
    ├── mysql
    ├── solr_dbpedia
    └── virtuoso-dbpedia

Uploading completed:
- [ ] agroknow
- [ ] iminds
- [ ] vtec
- [X] wripl

**Comment by jnehring** [comment]
@m1ci @sandroacoelho I think we should add a short documentation article about which triples need to be in Virtuoso and for which functionality. The only documentation is this GitHub issue and I think this is not clear. What do you think?

**Comment by m1ci** [comment]
@sandroacoelho can you write such article, please?
 
- entity  types: for general classification of entities, for domain specific NER
- entity labels: for attaching entity label via e-Link/pipelining
- DBpedia ontology: for most specific entity type (for DBpedia types)

I think these are the three use cases. @sandroacoelho did I miss something?

**Comment by sandroacoelho** [comment]
Hi @m1ci, @jnehring : I will do that.

**Comment by jnehring** [comment]
This issue is done.
