### ISSUE TITLE
Test the docker installation

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-docker#18]
See https://github.com/freme-project/freme-docker/wiki

**Comment by pheyvaer** [comment]
I've successfully installed FREME using docker. However, three remarks/questions:
- e-Translation timed out the first time, probably the VM at Tilde's side had to boot (?), so maybe as a test example another call would be better
- where are all the docker-compose elements stored that are being downloaded? Because it downloaded multiple gigs and the total size of the images is less than 3.5G.
- Do I also need to try to start the different containers one by one?

**Comment by fsasaki** [comment]
the docker compose page https://github.com/docker/compose/releases says:

> If you're a Mac or Windows user, the best way to install Compose and keep it up-to-date is Docker for Mac and Windows.

does this mean that Compose needs to be installed separately? Since the instructions for freme docker lists two separate prerequisites:

> Install docker
> Install docker-compose

**Comment by pheyvaer** [comment]
For Linux you need to do that.

**Comment by ghsnd** [comment]
I also successfully installed it.
The wiki adds 'sudo' to some docker commands, but this is not necessary if your user is in the 'docker' group.

**Comment by jnehring** [comment]
@pheyvaer @ghsnd thanks for testing! Im glad it worked out. Was the process straight forward or did you have to overcome any obstacles?

> e-Translation timed out the first time, probably the VM at Tilde's side had to boot (?), so maybe as a test example another call would be better

Good idea.

> where are all the docker-compose elements stored that are being downloaded? Because it downloaded multiple gigs and the total size of the images is less than 3.5G.

Hm good question. You can use `docker images` or `docker ps -a` to see the images. To save space you can also delete the images using `docker rm` or `docker rmi`.

> Do I also need to try to start the different containers one by one?

Nope, thats fine what you did.

> does this mean that Compose needs to be installed separately?

Yes. You need to install the two separately.

**Comment by pheyvaer** [comment]
> Hm good question. You can use docker images or docker ps -a to see the images. To save space you can also delete the images using docker rm.

That's about the docker images, but I think it downloaded way more that the total size of the images, no?

**Comment by jnehring** [comment]
I do not know how much it downloaded. Is this important? Do you know roughly how much it downloaded? The size of the 4 images that make up FREME sums up to around 3.5 GB.

**Comment by pheyvaer** [comment]
It is important if it is locally stored and not removed ;) because if it downloads 3.5G and makes images of 3.5G than that's already 7G, where you are not using half of it, once the images are created.
No, I didn't save the output.

**Comment by jnehring** [comment]
I suggest to clean up you use

`docker ps -a`
and then `docker rm` for each container.

afterwords you can use 

`docker images`
and `docker rmi` for each image

This should delete containers and images. I do not know of another cleanup method.

**Comment by jnehring** [comment]
done
