### ISSUE TITLE
Discussion: Add data to the containers or outside of the containers

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-docker#22]
In #16 and #17 we add data to the docker images.

@sandroacoelho propose solution a) to have one docker image of Virtuoso, another docker image of Solr. This image has configured a data folder outside of the container that stores the Virtuoso data / Solr data. So there is one small docker image. Further for Solr there are two versions of the data folder (one with all dbpedia datasets and europena and another one with all datasets). Same for Virtuoso.

I proposed solution b) to store the data directly in the image. This means that for Solr there are three images: One without data, one with all dbpedia datasets and euopreana, one with all datasets. Same for Virtuoso. Further there are three docker compose files, one for each configuration.

Pro a) According to @sandroacoelho it is easier to update the data in the images.

Pro b)
- It is easier to use then a) because there is less manual work. In a) you need to copy the correct data folders to the correct location and add some data to the mysql database as well.
- The docker images can stay on dockerhub for free even when the project lifetime has ended. Unlike solution b) which needs to find a solution where to store the data folders.

@sandroacoelho what do you think? The question of updatabillity is still not clear to me, can you please further explain why it is easier to update this?

**Comment by sandroacoelho** [comment]
Hi @jnehring ,

When the data is stored inside the image, it works like a "ROM" memory (It is an issue for B solution). Whenever you start FREME image, you can run read/write operations, but all write operations are not persistent. When you power-off the image and start again, all changes made by the users will be lost.

The benefits to having the data outside the Docker are: 
- We will have just images for software (separation of concerns);
- The users can choose to use the images with or without pre-loaded data justing using copy and paste operations;
- Backup / Restore simplification: the system administrator just has to backup folders used by storing Docker data;

> > @sandroacoelho what do you think? The question of updatabillity is still not clear to me, can you please further explain why it is easier to update this?

I have checked the documentation and unfortunately is not possible to merge the data using Docker layers like we have planned to use before.

When new DBpedia dumps versions were released,  it is necessary to re-index all these data like we are doing now to facilitate our users. With these dumps, the users just need to download and replace the files in their instances. We can ask for the DBpedia team to provide it for us.

**Comment by jnehring** [comment]
> When the data is stored inside the image, it works like a "ROM" memory (It is an issue for B solution). Whenever you start FREME image, you can run read/write operations, but all write operations are not persistent. When you power-off the image and start again, all changes made by the users will be lost.

This would be a real issue. But I am not sure if this is true. I tried with the MySQL database docker image. It is totally self contained and all data is stored in the image. I can add data and restart the image. The data is still there. So write operations can be made persistent.

I will test this behaviour.

**Comment by jnehring** [comment]
The ROM issue is not totally correct because we can define a volume in the image that provides read / write access.  After FREME has ended we have no other possiblity to store large files as docker hub. So I think we should add the data to the images simply because we have no other option.

We could host the data also as a data only container, this is a container that just stores the data. But I am not sure if this setup is useful.

**Comment by sandroacoelho** [comment]
Thanks for testing it.  I didn't know about that.

**Comment by jnehring** [comment]
I did not succeed in adding the data to a docker container. Although

**Comment by jnehring** [comment]
I did not succeed in adding the data to a docker image. I thought the [data container](http://container42.com/2013/12/16/persistent-volumes-with-docker-container-as-volume-pattern/) might solve the problem but it did not work out.

It is odd because the fremeproject/freme-mysql-data image has the sql database initialised with data and it works fine.

We are running out of time so I propose to not investigate this approach further and keep @sandroacoelho solution to keep the solr and virtuoso data outside of the image.

**Comment by jnehring** [comment]
This question is solved.
