### ISSUE TITLE
Question on freme-ner docker images

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-docker#23]
The [fremeproject dockerhub website](https://hub.docker.com/r/fremeproject/) lists a lot of docker images:
- fremeproject/freme-ner-en
- fremeproject/freme-ner-es
- fremeproject/freme-ner-fr
- fremeproject/freme-ner-ru
- fremeproject/freme-ner-it
- fremeproject/freme-ner-nl

IMO these can be deleted. @sandroacoelho is there a reason to keep them? When we do not delete them we need to document what they do.

**Comment by sandroacoelho** [comment]
We can delete it. I did for you.

**Comment by jnehring** [comment]
thanks :)
