### ISSUE TITLE
e-publishing not latest version

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/freme-docker#25]
On the Docker installation of DFKI, is the latest version of e-publishing installed? Because the [issue](https://github.com/freme-project/e-Publishing/issues/23) that was fixed, is giving an error now.

**Comment by jnehring** [comment]
i will check this

**Comment by Katsivelisp** [comment]
Hi, I just noticed too and was about to report this. :)

**Comment by jnehring** [comment]
it was not running the latest version. i updated it. please check again.

**Comment by pheyvaer** [comment]
I still get the error.

**Comment by jnehring** [comment]
ok i will further investigate.

**Comment by jnehring** [comment]
Something went wrong with the release. The current release contains e-publishing in version 0.5, but I have released e-publishing version 0.6. The same problem occurs on freme-dev and freme-live also.

So I will fix the release and install the latest version of e-publishing. I will do this tomorrow.

**Comment by jnehring** [comment]
I have updated e-publishing to the latest version and run the curl request from https://github.com/freme-project/e-Publishing/issues/23. IMO it works now. @pheyvaer please confirm.
