### ISSUE TITLE
Copy of server contains link to Tilde Dev version of services

### ISSUE THREAD

**Issue by andish** [freme-project/freme-docker#28]
Seems that  copy of FREME points to Tilde Development environment. Should be switched to the public version.

This curl shouldn't return an error:

```
curl -X POST -d 'Welcome to Berlin!' "http://rv2622.1blu.de:4000/e-translation/tilde/?source-lang=en&target-lang=de&informat=text"
```

**Comment by jnehring** [comment]
I think the problem lies within the CURL request. For some reason curl fails when you do not add a Content Type header. Try this request

```
curl -X POST -d 'Welcome to Berlin!' --header "Content-Type: text/plain" "http://rv2622.1blu.de:4000/e-translation/tilde/?source-lang=en&target-lang=de&informat=text"
```

I cannot reproduce the problem in Postman.

**Comment by andish** [comment]
Yes, it is now working also with my sample. 
Yesterday it returned "no MT system available" message (Dev environment do not have any system now).
