### ISSUE TITLE
DefaultGraph

### ISSUE THREAD

**Issue by sandroacoelho** [freme-project/freme-docker#31]
FREME NER is using [http://www.freme-project.eu/datasets/types](https://github.com/freme-project/freme-ner/blob/002c7c742b0609fc4c886ac2cbdd53b98f10fdbb/src/main/java/org/elinker/core/api/java/utils/SPARQLProcessor.java#L48) as a default graph.

Standardize it is a good idea, putting the same address in [Docker Compose](https://github.com/freme-project/freme-docker/blob/master/compose/docker-compose.yml#L33)  and provide this information in somewhere (will be useful as a future reference to prepare all virtuoso files as requested in issue #17).

As a solution, we can

1 - Leave this address blank or
2 - Create an entry in our application.properties to store this value (Eg.: freme.ner.sparqlDefaultGraph) and write about it in our documentation;

What should I do @m1ci , @jnehring ?

**Comment by m1ci** [comment]
>  1 - Leave this address blank or

+1 - but see if it will not cause some problems first. This relates to https://github.com/freme-project/freme-ner/issues/160#issuecomment-258388591

**Comment by jnehring** [comment]
Leaving it blank sounds simple. What are the implications of this? When people load data in Virtuoso, do they need to add it to the default graph? Or to the graph "http://www.freme-project.eu/datasets/types" ?

**Comment by sandroacoelho** [comment]
They need to add into default graph (blank) because we do not use  http://www.freme-project.eu/datasets/types anymore
