### ISSUE TITLE
FREME NER does not work in the docker installation

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-docker#33]
curl -X POST -H "Content-Type: text/plain" -H "Accept: text/turtle" -H "Cache-Control: no-cache" -H "Postman-Token: ba1b9f35-0e55-012d-d038-b6b300f5e073" -d 'The Eiffel Tower (/ˈaɪfəl ˈtaʊər/ EYE-fəl TOWR; French: tour Eiffel [tuʁ‿ɛfɛl] About this sound listen) is a wrought iron lattice tower on the Champ de Mars in Paris.' "http://rv2622.1blu.de:4000/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=all"

 takes forever and results in "ExternalServiceFailedException".

**Comment by sandroacoelho** [comment]
Hi @jnehring 

FREME-NER is fully connected on SOLR. 

Checking our docker-compose configuration, we have SOLR under 4001

```
[.....]
  freme-solr:
    image: fremeproject/freme-solr
    ports:
      - "4001:8890" 
[.....]
```

In our fremeproject/freme-broker image, we have SOLR under 8983 port (in  application.properties)

```
milan@rv2622:/opt/freme# docker exec -it 4c6994e3d32a /bin/sh
/ # cd freme-package/config
/freme-package/config # cat application.properties 
freme.ner.sparqlEndpoint=http://freme-virtuoso:8890/sparql
freme.ner.solrURI=http://freme-solr:8983/solr/
freme.ner.languages=en

[.....]

```

We need to put the service under the same port to work. (I did change nothing in the server someone is using FREME-LIVE right now and SOLR LIVE is running under 8983 port)

Best,

**Comment by jnehring** [comment]
That solved the problem. Great, thanks!
