### ISSUE TITLE
update docker images

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-docker#34]
Please update the docker containers

```
docker pull fremeproject/freme-broker
docker pull tenforce/virtuoso
docker pull fremeproject/freme-mysql-standard
docker pull fremeproject/freme-solr

docker-compose stop
docker-compose up -d --no-deps
```

and check if the docker installation works now.

**Comment by katia-vistatec** [comment]
I tried 
curl -X POST "http://localhost:4000/e-translation/tilde?input=hello+world&informat=text&source-lang=en&target-lang=de"

but I got an error:
[Error.txt](https://github.com/freme-project/freme-docker/files/611015/Error.txt)

**Comment by katia-vistatec** [comment]
In my case the name of these images are different: 
tenforce/virtuoso
fremeproject/freme-mysql-standard

**Comment by jnehring** [comment]
> tenforce/virtuoso
fremeproject/freme-mysql-standard

Right. I updated my GitHub comment so others dont have the same problem.

> but I got an error:
Error.txt

The problem is that you do not have enough memory (java.lang.OutOfMemoryError: GC overhead limit exceeded). How much memory does your VM have?

**Comment by katia-vistatec** [comment]
Which VM?

**Comment by jnehring** [comment]
I mean the virtual machine. I want to know how much RAM your server has. You can check with linux shell command "free -h".

**Comment by katia-vistatec** [comment]
Ok. The server has 32178 MB (Total), 14050 MB (Used),  18128 MB(Free). 
Is it not a problem of JVM?

**Comment by jnehring** [comment]
Maybe this is the problem:

https://github.com/freme-project/freme-docker/issues/37

I will check.

**Comment by jnehring** [comment]
Can you try to start FREME NER with english language only until we have solved the memory issue?

**Comment by katia-vistatec** [comment]
Yes. I have to find a CURL for FREME NER.
This is the result I get. No errors!
[curl and result.txt](https://github.com/freme-project/freme-docker/files/611606/curl.and.result.txt)

**Comment by jnehring** [comment]
No errors sounds great!

I close this issue. We solve the last issues with @pheyvaer and @ghsnd and then we can continue with the VTEC installation.
