### ISSUE TITLE
Basic version also loads English NER model

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/freme-docker#35]
The basic version also loads the English NER model. I thought it didn't load any models when you using basic?

**Comment by jnehring** [comment]
The [documentation](https://freme-project.github.io/knowledge-base/freme-for-sysadmins/use-freme-docker.html) says

> All FREME distributions contain all e-Services, all basic services and all FREME NER models. 

Please close the issue if it is clearer now.

**Comment by pheyvaer** [comment]
But then under 'standard' it says that the languages are added, which is not the case for the basic version. That part is confusing actually. It kinda contradicts itself.

**Comment by jnehring** [comment]
Now I see the misunderstanding. I added a few sentences to the overview section. Is it clearer now?

https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/use-freme-docker.html

**Comment by pheyvaer** [comment]
Thanks, it is clear now.
