### ISSUE TITLE
Set memory limit of broker

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/freme-docker#37]
The memory limit of `java` is set [here](https://github.com/freme-project/freme-docker/blob/master/freme-broker/Dockerfile#L7). However, when we load `en` and `nl` this is not enough. Is it possible to move this to a parameter, so we can set it via `docker-compose.yml` or `config.env`?

**Comment by jnehring** [comment]
I created a new version of fremeproject/freme-broker image that does not set Xmx in the Dockerfile and pushed it to dockerhub. Then I added this line to config.env, according to [this stackoverflow thread](http://stackoverflow.com/questions/29923531/how-to-set-java-heap-size-xms-xmx-inside-docker-container).

```
JAVA_OPTS='-Xmx5g'
```

Seems to work. I could start FREME NER with 4 languages en,nl,fr,de with this configuration.

**Comment by ghsnd** [comment]
I also tried this by putting `JAVA_OPTS='-Xmx5g'` in `config.env`. The `-Xmx3g` is gone indeed, but if I look at the process, I don't see a Xmx parameter at all. Here's the process listing of the broker process:

```
PID   PPID CMD
9461  9444 /bin/sh -c java -cp "freme-package/*:freme-package/config" -Djava.security.egd=file:/dev/./urandom  org.springframework.boot.loader.JarLauncher
9525  9461 java -cp freme-package/*:freme-package/config -Djava.security.egd=file:/dev/./urandom org.springframework.boot.loader.JarLauncher
```

@jnehring do you see your `-Xmx5g` parameter when you list the process?

**Comment by jnehring** [comment]
I dont see -Xmx5g parameter but this is fine. I think the processes list shows only the command line arguments that where passed to FREME. It does not show the environment variables. `JAVA_OPTS='-Xmx5g'` sets the XMX parameter as environment variable.

When I list the processes I get

```
/ # ps
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/sh -c java -cp "freme-package/*:freme-package/config" -Djava.secur
    7 root       9:49 java -cp freme-package/*:freme-package/config -Djava.security.egd=file:
   53 root       0:00 /bin/sh
   73 root       0:00 ps
/ #
/ # cat /proc/7/cmdline
java-cpfreme-package/*:freme-package/config-Djava.security.egd=file:/dev/./urandomorg.springframework.boot.loader.JarLauncher/ #
```

The odd thing is that no matter how I configure the -Xmx option I can always run FREME with all languages. without errors. The top command reveils, that FREME uses 16 GB of RAM. So I cannot reproduce the error. Can you please further describe the problem in more detail? I guess you try to start FREME and then you get an Out Of Memory error?

I pushed a new version of the broker to dockerhub to remove the Xmx settings from start-arguments file. This should not have an influence on this issue but pull the new broker image.

**Comment by ghsnd** [comment]
I also noticed that, no matter the value of `xmx`, the process always got the same amount of memory. I suspect that the process is just not reading `JAVA_OPTS`, and thus takes the standard percentage of your available RAM memory . This environment variable is also Tomcat-specific; does our Spring Boot app launch Tomcat?

In [this post](https://medium.com/@cl4r1ty/docker-spring-boot-and-java-opts-ba381c818fa2#.ycptg0t48), `$JAVA_OPTS` is explicitly passed as argument, in `ENTRYPOINT` in the docker file.

Maybe something like this can be added in the dockerfile of the broker:

    ENTRYPOINT java $JAVA_OPTS -cp "freme-package/*:freme-package/config" -Djava.security.egd=file:/dev/./urandom  org.springframework.boot.loader.JarLauncher

where `JAVA_OPTS` is defined in `config.env` ? Dit not test this yet.

**Comment by ghsnd** [comment]
Just reopening it to test (@jnehring) ... Also, a new container with the fix still has to be pushed. Will you do that?

**Comment by jnehring** [comment]
I tested it and it works for me also. I updated the [documentation](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/use-freme-docker.html) to mention the new parameter and a method on how to calculate the ram usage of FREME.

**Comment by jnehring** [comment]
I also push the new broker.

**Comment by katia-vistatec** [comment]
So I can try also to see if it works for me.

**Comment by jnehring** [comment]
> So I can try also to see if it works for me.

Yes please. You need to pull the latest broker and update your config.env file to add the new configuration option.

**Comment by katia-vistatec** [comment]
It doesn't seem to work for me

**Comment by ghsnd** [comment]
Indeed, I tried a fresh install and saw this message in the log:

    freme-broker_1    | Error: Could not find or load main class '-Xmx5g'

Will look into this tomorrow...

**Comment by katia-vistatec** [comment]
Really weird but now it seems to work. This is what I obtain with the test curl in the documentation:
curl -X POST "http://localhost:4000/e-translation/tilde?input=hello+world&informat=text&source-lang=en&target-lang=de"
<http://freme-project.eu/#char=0,11>
        a                    nif:String , nif:RFC5147String , nif:Context ;
        nif:beginIndex       "0"^^xsd:nonNegativeInteger ;
        nif:endIndex         "11"^^xsd:nonNegativeInteger ;
        nif:isString         "hello world"^^xsd:string ;
        itsrdf:mtConfidence  "0.774042332734315" ;
        itsrdf:target        "guten Tag weltweit"@de .

**Comment by katia-vistatec** [comment]
Before logging off I checked that the JAVA_OPTS environment variable was read inside the freme broker container. When I logged in again to check if I had the same error I found no error.

**Comment by jnehring** [comment]
> Indeed, I tried a fresh install and saw this message in the log:

> freme-broker_1    | Error: Could not find or load main class '-Xmx5g'

I do not get this error.

**Comment by ghsnd** [comment]
My install was not entirely fresh. I did it again this morning, and now it all works. I think we can consider this issue closed.
