### ISSUE TITLE
Separate API keys for Tilde services

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-docker#38]
In https://github.com/freme-project/e-services/issues/39 we have implemented the functionality to pass an authentication parameter to the tilde services. Now each partner should get his own key and add this to his configuration. Tilde can then find out who uses the Tilde APIs,

@andis is it still a requirement from Tilde that everybody uses their own API keys? In this case you should send the API keys to WRIPL, VTEC, Agroknow and iMinds. DFKI already has an API key.

**Comment by andish** [comment]
Yes, we will provide different authentication parameter for each
installation.

**Comment by borriellom** [comment]
We have received the authentication token (thank you @andish) and will use it in our custom installation.
Anyway Tilde services are failing on both dev and live version of FREME. The error says "unauthorized". I guess that also those versions should be updated with the authorization token. 
@jnehring  could you update at least the dev version please?

**Comment by andish** [comment]
Hmm, it should work. There is also token for this current installation.
Maybe something wrong with reading the token from application configuration file : application.properties

**Comment by andish** [comment]
Created pull requests. For both services there were wrong http headers named (should be "Authorization" not "Authentication" for Basic Authentication)

**Comment by jnehring** [comment]
To configure the authentication key for Tilde in docker installation you can put this configuration in your config.env file:

```
TILDE_TRANSLATION_AUTHENTICATION=Basic {your authentication token }
TILDE_TERMINOLOGY_AUTHENTICATION=Basic {your authentication token }
```

I will add this to the docker documentation.

The latest bugfix of this feature is currently not installed in the freme-broker docker image. I will post a comment in this issue when the freme-broker image is updated with the bugfix.

**Comment by katia-vistatec** [comment]
I updated the config.env file but it does not work. When I do 
curl -X POST "http://localhost:4000/e-translation/tilde?input=hello+world&informat=text&source-lang=en&target-lang=de"
I got an exception:

{
  "exception": "eu.freme.common.exception.ExternalServiceFailedException",
  "path": "/e-translation/tilde",
  "message": "External service failed: ",
  "error": "Unauthorized",
  "status": 401,
  "timestamp": 1481033885137
}

**Comment by jnehring** [comment]
The latest bugfix is not in the current docker image so this is the same error as [this comment](https://github.com/freme-project/freme-docker/issues/38#issuecomment-264472599). Please try another API call, e.g.

curl -X POST -d 'Welcome to Berlin!' "http://localhost:4000/e-entity/freme-ner/documents?language=en&informat=text&mode=spot"

**Comment by katia-vistatec** [comment]
This one with freme-ner works. Only those with Tilde do not work. Are you going to update the new image in the next days? If not I can work on https://github.com/freme-project/freme-docker/issues/39 commenting this configuration in config.env.

**Comment by jnehring** [comment]
I can update the docker image tomorrow.

**Comment by andish** [comment]
When it is planned to release the FREME public server? If not planned soon, than we have to to create temporal fix for Tilde services to make it work in public environment.

**Comment by jnehring** [comment]
@katia-vistatec I created a new docker image for the broker. For the DFKI installation this solved the problem. Can you please try?

```
cd /opt/freme
docker pull fremeproject/freme-broker
docker-compose stop freme-broker
docker-compose up -d --no-deps freme-broker
```

@andish 
>When it is planned to release the FREME public server? If not planned soon, than we have to to create temporal fix for Tilde services to make it work in public environment.

I can make a release next week.

**Comment by katia-vistatec** [comment]
@jnehring I tried and It works.

**Comment by jnehring** [comment]
Ok. Could you also add your authentication token to the installation?

**Comment by katia-vistatec** [comment]
Yes I did in the config.env file.

**Comment by jnehring** [comment]
Ok great. then this issue is solved.

**Comment by jnehring** [comment]
I reopen the issue to remind me to test if the bug is fixed on freme-live after next release

**Comment by jnehring** [comment]
fixed through the release: https://github.com/freme-project/technical-discussion/issues/127
