### ISSUE TITLE
FREME test suite

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-docker#39]
To verify that FREME works after an installation I created a test suite using the [automated test feature](http://blog.getpostman.com/2014/03/07/writing-automated-tests-for-apis-using-postman/) of postman. Using the test suite you can execute a series of postman requests. The HTTP response of the requests will be matched against a set of rules.

To execute it

1. [Download the collection](https://github.com/freme-project/freme-docker/files/624032/FREME.20TEST.postman_collection.json.txt), remove the ".txt" in the end so the file type is ".json"
2. Import it into Postman
3. Create environment with variable "baseUrl" that points to the API you want to test (more information on this [here](https://freme-project.github.io/knowledge-base/freme-for-api-users/gettingStarted_API-users.html)
4. Press "Runner" (upper left corner of the screen)
5. Select collection "FREME TEST" and your newly created environment
6. Press "Start Test"

Currently it does not write any data. It performs API calls from the Postman collection and checks if the response code is 200. It runs these tests

* e-Translation
* freme-ner
* e-Terminology
* e-link
* get all datasets
* get all templates
* filter - knowledgebase example
* get all filter
* get all pipelines
* nif-converter xml
* get all users
* tei2temp-html
* get all xslt-converters

@ghsnd when you find the time you might try to execute the tests to check if it works for you and if it detects any errors in your installation.

**Comment by ghsnd** [comment]
One test fails (**e-link example API call**), but this is probably because I have no templates:

```javascript
{
  "exception": "eu.freme.common.exception.TemplateNotFoundException",
  "path": "/e-link/documents",
  "message": "Can not find Template with id='1'",
  "error": "Not Found",
  "status": 404,
  "timestamp": 1480603249865
}
```
All other tests pass.

**Comment by ghsnd** [comment]
Strange though that having no templates causes an error rather than an empty list in the response...

**Comment by jnehring** [comment]
Thanks for testing! You have templates but they have the wrong IDs (see #41). Therefore the e-link example API call that uses template id 1 fails. This issue should be fixed after an update of the mysql container.

**Comment by ghsnd** [comment]
OK, updated the container, all tests pass!

**Comment by jnehring** [comment]
Next steps

1) Add HTML example to the test suite to test e-Internationalization
2) Add the test suite to the freme documentation

**Comment by jnehring** [comment]
@bgrusdt please 

* Add two e-Internationalization tests to the test suite. One should convert HTML to NIF, the other one should to HTML roundtripping. Use FREME NER endpoint for the test. Just test if the response code is 200.
* Store the test suite in the API documentation homepage somewhere in https://github.com/freme-project/freme-project.github.io/tree/dev/resources . Then add an explanation how to use it to [getting started for system administrators guide](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/gettingStarted_SysAdmins.html). You can re-use the instructions I wrote in the first comment of this issue.
* Add links to the article about the test suite to these articles and mention that after the installation is finished it can be tested using the test suite.
    * https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/start-and-run-freme.html
    * https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/use-freme-docker.html

**Comment by bgrusdt** [comment]
@jnehring  I added the tests to the TEST Suite and uploaded it [here](https://github.com/freme-project/freme-project.github.io/blob/dev/resources/postman/FREME-TEST.postman_collection).

[This](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/gettingStarted_SysAdmins.html) is the information I added to the getting started Article. 
I also added the links to the two articles:

in start-and-run-freme
* When the installation is finished you can test it using the Test Suite which is described in the [Getting started article](gettingStarted_SysAdmins.html).

and in freme-docker
* You can test if the installation was succesful by using the Test Suite which is described in the [Getting started article](gettingStarted_SysAdmins.html).

**Comment by jnehring** [comment]
Thank you. I changed the file ending of the collection to ".json", removed the part of the instruction that says "rename to json". Then I changed the download link to point directly to the raw file instead of the github page.

So this issue is finished!

**Comment by katia-vistatec** [comment]
Hi Jan I haven't done the tests so far.

**Comment by katia-vistatec** [comment]
I also executed the tests of the collection and it worked.
