### ISSUE TITLE
Write freme-docker documentation

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-docker#8]

**Comment by jnehring** [comment]
Started to collect documentation here: https://github.com/freme-project/freme-docker/wiki

**Comment by jnehring** [comment]
The guide how to install FREME in docker is finished: https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/use-freme-docker.html

The old information in the wiki is not important. I will use this installation to write a second guide how to maintain the docker files.

**Comment by jnehring** [comment]
done: https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/maintain-freme-docker.html

@ghsnd you can find information how to build the broker in the guide

**Comment by ghsnd** [comment]
Alright, I can build it now, thanks!
I changed the docs slightly...
