### ISSUE TITLE
access control to web uis

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-docker#9]
The system has many web uis. It might be a good idea to hide them from the open web. Maybe this is more a question of the cloud that hosts the system (e.g. amazon) then of the docker configuration itself.

**Comment by jnehring** [comment]
related to #10

**Comment by pheyvaer** [comment]
So all these web uis are offered via a different port, right?

**Comment by jnehring** [comment]
right

**Comment by pheyvaer** [comment]
I've had a look at Amazon for deploying a docker container. A quick guide can be found [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html). Regarding the different uis, you can open the required ports using the `-p` option, as explained in the aforementioned guide and [here](https://docs.docker.com/engine/reference/run/#/expose-incoming-ports). This will link a port of the host with the port of the container. So `-p 80:80` will link port 80 of both. However, whether the public will be able to access these ports depends on the settings of the Amazon machine. Hence, is outside of the scope of the Docker container. Users deploying FREME can choose themselves how they want to it. Does this answer your question?

**Comment by jnehring** [comment]
We can discuss tomorrow. I know about the -p parameter in docker but it does not solve the problem. These web UIs should be
- accessible for the administrators, that means for the business case partners.
- not accesible for anybody else.

Possible solutions are (this is only a brainstorming)
- password protect them one by one - i guess this is a lot of work.
- have an entry in the iptables that open the respective ports only for the business case partners IP adress. This is easy but not very elegant.
- maybe amazon offers another solution?

**Comment by jnehring** [comment]
For a start we will just make all UIs accessible for nobody. If anyone needs these UIs we can find an appropriate solution.
